# Generated by Django 4.2.3 on 2023-07-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cost', models.FloatField()),
                ('amount', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField()),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('includes_items', models.BooleanField(default=False)),
                ('is_income', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.category')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.record')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.ManyToManyField(through='bookkeeping.RecordCategory', to='bookkeeping.category'),
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.category')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(through='bookkeeping.ItemCategory', to='bookkeeping.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.record'),
        ),
    ]
