# Generated by Django 4.2.3 on 2023-09-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ManyToManyField(null=True, through='bookkeeping.RecordCategory', to='bookkeeping.category'),
        ),
    ]
