# Generated by Django 4.2.3 on 2023-09-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_alter_record_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.item'),
        ),
    ]
